services:
  petuh:
    image: 192.168.0.201:30500/petuh:0.13.105
    platform: linux/amd64
    container_name: petuh
    restart: unless-stopped
    networks:
      - petuh-net

  petuh-llm:
    image: 192.168.0.201:30500/petuh-llm:0.13.105
    platform: linux/amd64
    container_name: petuh-llm
    restart: unless-stopped
    ports:
      - "50051:50051"
    networks:
      - petuh-net
  
  petuh-data:
    image: 192.168.0.201:30500/petuh-data:0.13.105
    platform: linux/amd64
    container_name: petuh-data
    restart: unless-stopped
    ports:
      - "50051:50051"
    networks:
      - petuh-net

networks:
  petuh-net:
    driver: bridge
