services:
  petuh:
    image: 192.168.0.201:30500/petuh:0.17.103
    platform: linux/amd64
    container_name: petuh
    restart: unless-stopped
    environment:
      - STAGING=true
    volumes:
      - ./logs:/app/logs
    networks:
      - petuh-net

  petuh-llm:
    image: 192.168.0.201:30500/petuh-llm:0.17.103
    platform: linux/amd64
    container_name: petuh-llm
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      - STAGING=true
    volumes:
      - ./logs:/app/logs
    networks:
      - petuh-net

  petuh-data:
    image: 192.168.0.201:30500/petuh-data:0.17.103
    platform: linux/amd64
    container_name: petuh-data
    restart: unless-stopped
    ports:
      - "50052:50052"
    environment:
      - STAGING=true
    volumes:
      - ./logs:/app/logs
    networks:
      - petuh-net

  pg-rw:
    image: postgres:17
    environment:
      POSTGRES_USER: petuh
      POSTGRES_PASSWORD: petuh
      POSTGRES_DB: petuh_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - petuh-net

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - petuh-net

  kafka:
    image:
      apache/kafka:4.0.1-rc0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - petuh-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  postgres_data:
  kafka_data:

networks:
  petuh-net:
    driver: bridge
