[package]
edition.workspace = true
name = "petuh-tests"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
redis = { workspace = true }

common = { workspace = true }
