apiVersion: v1
kind: Namespace
metadata:
  name: petuh
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: petuh-longhorn-pv
  namespace: petuh
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    volumeHandle: petuh  # <-- This must match the name of the volume in Longhorn exactly
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
