apiVersion: v1
kind: Namespace
metadata:
  name: petuh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petuh
  namespace: petuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petuh
  template:
    metadata:
      labels:
        app: petuh
    spec:
      containers:
        - name: petuh
          image: 192.168.0.201:30500/petuh:0.13.103
#          volumeMounts:
#            - mountPath: /datadir
#              name: datadir
#      volumes:
#        - name: datadir
#          persistentVolumeClaim:
#            claimName: petuh-longhorn-pvc

#  kubectl scale deployment petuh --replicas=0 -n petuh

