[package]
name = "petuh"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
dotenv = { workspace = true }
fake = { workspace = true }
sentry = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
teloxide = { workspace = true }
tokio = { workspace = true }
uname = { workspace = true }
whoami = { workspace = true }

#store = { workspace = true }
