apiVersion: v1
kind: Namespace
metadata:
  name: petuh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petuh
  namespace: petuh
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: petuh
  template:
    metadata:
      labels:
        app: petuh
    spec:
      containers:
        - name: petuh
          image: 192.168.0.201:30500/petuh:0.14.109
