apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
  namespace: petuh
spec:
  instances: 3

  postgresql:
    parameters:
      max_connections: "200"

  bootstrap:
    initdb:
      database: petuh_db
      owner: petuh
      secret:
        name: postgres-credentials

  storage:
    size: 1Gi
    storageClass: "local-path"
---
apiVersion: v1
kind: Service
metadata:
  name: pg-rw-nodeport
  namespace: petuh
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
      protocol: TCP
  selector:
    cnpg.io/cluster: pg
    cnpg.io/instanceRole: primary
